### ISSUE TITLE
Getting an error NatsError: filter subject can not be updated

### ISSUE THREAD

**Issue by romit-gandhi** [nats-io/nats.js#491]
I'm using NATS Jetstream as communication channel between different microservices.

I'm using NATS Jetstream in the kubernetes cluster 

```
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: demostream
spec:
  name: demostream
  subjects: ["demo.*"]
  storage: memory
  servers: ["nats-srv:4222"]
  maxAge: 1h
```

Using this I'm creating the stream. After that I'm able to publish the events from one service with the topic **demo.user:created** and **demo.user:updated**. Now in the another service when I'm trying to listen this 2 events I'm getting an error **NatsError: filter subject can not be updated**. If I comment the code of one listener then it is working perfectly but when I'm trying with multiple listeners this error pops up. Can anyone help me with this issue?

Thank you so much.
