### ISSUE TITLE
[jetstream] Consumer disconnecting after one cluster node restarts

### ISSUE THREAD

**Issue by Mikxail** [nats-io/nats.js#570]
I have nats cluster with 3 nodes. Everything works correctly when one node down. But when node is restored - consumer are disconnected.

Steps for reproduce.
1. Run nats cluster
2. Create jestream. Storage - "File", Replicas count - 3
3. Connect and subscribe to stream
4. Kill one node (doesn't matter leader or replica node)
5. everything woks fine
6. Restore replica
7. Consumer will be disconnected

<details>
<summary>Consumer script</summary>

```
const nats = require('nats');

const SERVERS = ['localhost:4222', 'localhost:4223', 'localhost:4224'];

const STREAM_NAME = 'stream1';

const SUBJECT_NAME = 'stream-subject';

(async () => {
    const nc = await nats.connect({
        servers: SERVERS,
        pingInterval: 3000,
        reconnect: true,
        maxReconnectAttempts: -1,
        debug: true
    });

    const iter = nc.status();
    (async () => {
        for await (const e of iter) {
            console.log('---EVENT: ', e);
        }
    })().then();

    const jsm = await nc.jetstreamManager();

    try {
        await jsm.streams.delete(STREAM_NAME);
    } catch (err) {}

    await jsm.streams.add({
        name: STREAM_NAME,
        subjects: [SUBJECT_NAME],
        num_replicas: 3,
        retention: 'workqueue',
        storage: 'file'
        // storage: 'memory'
    });

    const js = nc.jetstream();

    const opts = nats.consumerOpts().manualAck().ackExplicit().maxAckPending(1).idleHeartbeat(1000).deliverTo(nats.createInbox());
    opts.callback((err, msg) => {
        console.log('=== MSG: ', err, msg);
    });

    await js.subscribe(SUBJECT_NAME, opts);
})();
```
</details>

<details>
<summary>Docker compose file</summary>

```
version: "3.5"

services:
  nats-1:
    image: nats:2.9.16-alpine3.17
    restart: unless-stopped
    ports:
      - 4222:4222
      - 8222:8222
    command: "--cluster_name NATS --jetstream --server_name=nats-1 --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-1:6222,nats://ruser:T0pS3cr3t@nats-2:6222,nats://ruser:T0pS3cr3t@nats-3:6222 --http_port 8222"
    networks:
      - nats-one

  nats-2:
    image: nats:2.9.16-alpine3.17
    restart: unless-stopped
    ports:
      - 4223:4222
    command: "--cluster_name NATS --jetstream --server_name=nats-2 --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-1:6222,nats://ruser:T0pS3cr3t@nats-2:6222,nats://ruser:T0pS3cr3t@nats-3:6222"
    depends_on:
      - nats-1
    networks:
      - nats-one

  nats-3:
    image: nats:2.9.16-alpine3.17
    restart: unless-stopped
    ports:
      - 4224:4222
    command: "--cluster_name NATS --jetstream --server_name=nats-3 --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats-1:6222,nats://ruser:T0pS3cr3t@nats-2:6222,nats://ruser:T0pS3cr3t@nats-3:6222"
    depends_on:
      - nats-1
    networks:
      - nats-one

networks:
  nats-one:
    name: "nats-one"
```
</details>

It reproduced for push and pull consumers.
But reproduced only on file storage. When I use memory storage everything works fine.
